### ISSUE TITLE
Request select2 tagging support

### ISSUE THREAD

**Issue by fahmij8** [Pharaonic/livewire-select2#1]
First of all, great work bro!
But, it'll be nice if you add the [tagging support](https://select2.org/tagging) as well.

**Comment by MoamenEltouny** [comment]
Thank you @fahmij8 
ok will ok on it.

**Comment by MoamenEltouny** [comment]
@fahmij8 it should be available now  👍🏻 

just add `data-tags` attribute

**Comment by fahmij8** [comment]
Thank you so much!
