### ISSUE TITLE
data not load after remove selection

### ISSUE THREAD

**Issue by ozonerik** [Pharaonic/livewire-select2#2]
![Video_22-03-15_12-42-27](https://user-images.githubusercontent.com/49719997/158314508-1f8bf4bc-ce36-42c1-a578-9c80eec39fda.gif)

Data not load after remove. selection multiple on livewire using modal bootsrap

**Comment by MoamenEltouny** [comment]
@ozonerik  Did you use [data-parent](https://pharaonic.io/packages/livewire/select2/1.x#attributes) attribute?
