### ISSUE TITLE
Nested Dropdown

### ISSUE THREAD

**Issue by masadi** [Pharaonic/livewire-select2#4]
How to use this repo for nested dropdown like selecting province then city and so on?

Thanks

**Comment by MoamenEltouny** [comment]
@masadi do you mean optgroup ?

**Comment by masadi** [comment]
@MoamenEltouny like this http://jsfiddle.net/greglockwood/T7LJY/3

**Comment by MoamenEltouny** [comment]
@masadi i don't think it's supported in Select2 Plugin at all .. but i believe that you can create it with livewire itself 
it's not related to our package

**Comment by masadi** [comment]
@MoamenEltouny here is another example using laravel 8 and ajax
http://ilmukita.org/laravel-8-membuat-dynamic-dependent-dropdown-menggunakan-select2/

**Comment by masadi** [comment]
@MoamenEltouny SOLVED

```
window.addEventListener('component_updated', event => {
        $.each(event.detail.data_array, function (i, item) {
            $('#sub_select').append($('<option>', { 
                value: item.value,
                text : item.text
            }));
        });
    })
```
