### ISSUE TITLE
Remove Selected Item

### ISSUE THREAD

**Issue by masadi** [Pharaonic/livewire-select2#5]
How to remove selected item after data saved?

**Comment by MoamenEltouny** [comment]
can you explain your issue please?

**Comment by masadi** [comment]
Like this 
https://select2.org/programmatic-control/add-select-clear-items

Selected
$('#mySelect2').val('1'); // Select the option with a value of '1'
$('#mySelect2').trigger('change'); // Notify any JS components that the value changed

Remove selected
$('#mySelect2').val(''); // Select the option with a value of null
$('#mySelect2').trigger('change'); // Notify any JS components that the value changed

**Comment by MoamenEltouny** [comment]
@masadi i think its good idea if we add new events that can called from livewire component to manipulate the options of select.
i will work on that soon
