### ISSUE TITLE
option disappear

### ISSUE THREAD

**Issue by ree-grestark** [Pharaonic/livewire-select2#7]
![image](https://user-images.githubusercontent.com/73009510/203480275-6cf8bd75-213e-4f5b-a3f1-dc1cd1e63dd5.png)
I already include all js and css from documentation, but the option seems overridden by the select2

and can you explain where should this code placed?
// Init Event
$this->dispatchBrowserEvent('pharaonic.select2.init');
 
// Load Event
$this->dispatchBrowserEvent('pharaonic.select2.load', [
    'component' => $this->id,
    'target'    => '#input-here'
]);

**Comment by MoamenEltouny** [comment]
`$this->dispatchBrowserEvent('pharaonic.select2.init');` to reload all the Select2

`$this->dispatchBrowserEvent('pharaonic.select2.load', [
'component' => $this->id,
'target' => '#input-here'
]);`
to reload a specific Select2 input
