### ISSUE TITLE
Request add allowClear option/attributes 

### ISSUE THREAD

**Issue by masadi** [Pharaonic/livewire-select2#8]
Great work!
![image](https://user-images.githubusercontent.com/5530849/204100005-cf1b0574-8f46-410d-b422-fc24b89f3325.png)

**Comment by MoamenEltouny** [comment]
Hello @masadi 
OK, I'll work on that today

**Comment by MoamenEltouny** [comment]
@masadi install the latest version
Added `data-clear` attribute
https://pharaonic.io/packages/livewire/select2/1.x#attributes
